spring:
  application:
    name: checklist
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/checklist_api?useTimezone=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

cors:
  allowedOrigin: http://localhost:3000

api:
  security:
    token:
      secret: ${JWT_SECRET:123}
      expiration: ${JWT_EXPIRATION:1800} #30 min #in seconds
      refresh-expiration: ${JWT_REFRESH:604800} #7 days #in seconds
      issuer: api_checklist.com.br

logging:
  level:
    org:
    springframework:
      security: DEBUG